<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\build\Common.Core.props" />
  <Import Project="..\..\build\NuGet.props" />

  <!-- Official Version -->
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <MajorVersion>3</MajorVersion>
    <MinorVersion>0</MinorVersion>
    <PatchVersion>0</PatchVersion>
    <VersionSuffix></VersionSuffix>
    <Version>$(MajorVersion).$(MinorVersion).$(PatchVersion)$(VersionSuffix)</Version>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>NSwag.AspNetCore.Themes</PackageId>
    <Description>
      Modernize your ASP.NET Core Swagger UI with runtime theme switching, deep customization, and new functional UI features.
    </Description>
    <PackageTags>
      swagger;swagger-ui;swaggerui;nswag;aspnetcore;webapi;openapi;extension;modern-ui;theme;dark-mode;dark-theme;runtime-theming;theme-switcher;theme-changer;custom-themes
    </PackageTags>
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSwag.AspNetCore" Version="14.6.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AspNetCore.Swagger.Themes.Common\AspNetCore.Swagger.Themes.Common.csproj" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificBuildOutput>$(TargetsForTfmSpecificBuildOutput);CopyProjectReferencesToPackage</TargetsForTfmSpecificBuildOutput>
  </PropertyGroup>
  <Target Name="CopyProjectReferencesToPackage" DependsOnTargets="ResolveReferences">
    <ItemGroup>
      <BuildOutputInPackage Include="$(OutputPath)AspNetCore.Swagger.Themes.Common.dll" />
    </ItemGroup>
  </Target>

</Project>