name: 🐞 Bug or error report
description: Report an anomaly or unexpected behavior with a sample from this repository.
title: "[Bug]: "
labels: ['needs: triage', 'bug-suspected']

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to complete this bug report!
  - type: checkboxes
    id: terms
    attributes:
      label: Guidelines
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/jessesquires/.github/blob/main/CONTRIBUTING.md).
      options:
        - label: I agree to follow this project's Contributing Guidelines.
          required: true
  - type: input
    id: project
    attributes:
      label: Project Version
      description: Which project versions are affected?
      placeholder: "1.0, 2.2, 3.5.1"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Clearly and concisely describe the bug.

        **Do not attach ZIP files** of your code or compiled projects - instead, please publish your code to a public GitHub repo & post a link to it.
      placeholder: Tell us what happened.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How do you reproduce this? Please provide as much step-by-step detail as possible.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen when the reproduce steps are followed?
      placeholder: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Add any other useful information about the problem here.
      placeholder: Is there any additional helpful information you can share?
    validations:
      required: false