<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\build\Common.Core.props" />
  <Import Project="..\..\build\Versioning.Extensions.props" />
  <Import Project="..\..\build\NuGet.props" />

  <PropertyGroup>
    <PackageId>NSwag.AspNetCore.Extensions</PackageId>
    <Description>
      Enhance your ASP.NET Core Swagger UI with functional extensions like API Counter.
    </Description>
    <PackageTags>
      swagger;swagger-ui;swaggerui;nswag;aspnetcore;webapi;openapi;extension;api-counter;operation-count;tag-extensions
    </PackageTags>
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
  </ItemGroup>

</Project>
