name: Pack

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

env:
    PROJECTS_PATH: 'src/*'
    PACKAGE_OUTPUT: ${{ github.workspace }}/artifacts
    NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          src

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Pack
      run: |
        dotnet pack ${{ env.PROJECTS_PATH }} --configuration Release --output ${{ env.PACKAGE_OUTPUT }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ${{ env.PACKAGE_OUTPUT }}
