name: Pack

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          src

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Pack
      run: |
        dotnet pack --configuration Release --output ${{github.workspace}}/artifacts

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ${{github.workspace}}/artifacts
